
server:
  port: 8080
  tomcat:
    max-http-form-post-size: -1

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/osdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  freemarker:
    cache: false
    checkTemplateLocation: true
    contentType: text/html
    suffix: .html
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates

mybatis:
  type-aliases-package: com.qicong.os
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.qicong.os.dao: debug
